# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://20joseph10.github.io/nbdev_tutorial/"

git_url = "https://github.com/20joseph10/nbdev_tutorial/tree/master/"

def custom_doc_links(name): return None
